import { SessionPayload } from "@models/SessionPayloadModel"
import { User } from "@models/UserModel"
import { Response } from "express"
import sqlConnection from "@utils/SQLConnection"
import { UserAPIError } from "@models/ErrorModels"
import { createHash } from "crypto"
import { invalidateSession } from "@controllers/auth/SessionController"
import redisConnection from "@utils/RedisConnection"

async function editUserInfoController(sessionPayload: SessionPayload, field: string, body: any, res: Response) {
    try {
        // Check if the field to patch has been defined
       if (field == undefined || field.length < ("name".length)) {
            throw new UserAPIError(
                400, 
                "ERR_MISSING_FIELD",
                "You must define the field you want to patch"
            )
        }
        const userInfo: User = await sqlConnection.getEntity(User, { email: sessionPayload.email }) as User
        const newFieldValue: string = body[field]

        // Check if the new field value exists in the body
        if(newFieldValue == undefined || newFieldValue.length == 0) {
            throw new UserAPIError(
                400,
                "ERR_MISSING_FIELD_VALUE",
                "You must define the new field value"
            )
        }
        
        if(field == "password") {
            const newPassword = createHash('sha256').update(newFieldValue).digest('hex');
            userInfo.passwordHash = newPassword;
        } else {
            const key = field as keyof User;
            userInfo[key] = newFieldValue;
        }
        // TODO: Produce PubSub Event "EmailChanged"
        sqlConnection.updateEntity(User, { email: sessionPayload.email}, userInfo);
        if(field == "email") {
            redisConnection.deleteValue(`jwt:session:${sessionPayload.email}`);
        }
        res.status(200).json({ success: true });

    }
    catch (error) {
        if (error instanceof UserAPIError) {
            res
                .status(error.httpCode)
                .json({
                    errorString: error.errorString,
                    errorMessage: error.message
                })
        }
        else {
            res
                .status(500)
                .json({
                    errorString: "ERR_INTERNAL_SERVER",
                    errorMessage: "Error generated by the server"
                })
            console.log(error)
        }
    }
}

export default editUserInfoController