apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emezon-application-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/v1/users(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: users-api-server
                port:
                  number: {{.Values.microservices.exposePort}}
