apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-db
spec:
  selector:
    matchLabels:
      app: redis-db
  serviceName: "redis-cache"
  replicas: {{ .Values.redis.replicasCount }}
  template:
    metadata:
      labels:
        app: redis-db
    spec:
      containers:
      - name: redis-db
        image: {{ .Values.redis.imageRegistryUrl }}redis:{{ .Values.redis.imageTag }}
        ports:
        - containerPort: 6379
          name: cache-ingress
---
apiVersion: v1
kind: Service
metadata:
  name: redis-db
spec:
  type: ClusterIP
  selector:
    app: redis-db
  ports:
  - port: 6379
    targetPort: 6379